# develop stage
FROM node:14.19-alpine as develop-stage
WORKDIR /app

COPY package*.json ./
COPY docker/nginx/* ./
RUN yarn global add @quasar/cli

COPY . .

# build stage
FROM develop-stage as build-stage
RUN yarn
RUN quasar build
RUN ls .

# production stage
FROM nginx:1.17.5-alpine as production-stage
#COPY --from=build-stage /app/default.conf /etc/nginx/default.conf
COPY --from=build-stage /app/mime.types /etc/nginx/mime.types
COPY --from=build-stage /app/nginx.conf /etc/nginx/nginx.conf

COPY --from=build-stage /app/dist/spa /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]


